name: JBiPLaw.com
favicon: null
layout_spectrum: 0.6380353351123631
typography_spectrum: 0.9359508878551424
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.2387033177074045
  lightness: 0.896561780711636
  saturation: 0.05453431000933051
  rhythmicContrast: 0.23601185414008796
purpose: []
